version: '3'

services:
  talker:
    image: ros:foxy-display
    command: ros2 run demo_nodes_cpp talker
    environment:
            - DISPLAY=${DISPLAY}
    volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode : host
  listener:
    image: ros:foxy-display
    command: ros2 run demo_nodes_cpp listener
    depends_on:
      - talker
